language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WP_VERSION=4.7 WP_MULTISITE=1 PHPLINT=1 PHPCS=1 COVERAGE=1
    - php: 5.2
      env: WP_VERSION=4.6 WP_MULTISITE=1 PHPLINT=1
    - php: 5.3
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=4.4
    # WP >= 4.7 is needed for PHP 7.1
    - php: 7.1
      env: WP_VERSION=4.7
    - php: hhvm
      env: WP_VERSION=4.7
    - php: 5.2
      env: WP_VERSION=master
    - php: nightly
      env: WP_VERSION=master
  allow_failures:
    # Allow failures for unstable builds.
    - php: nightly
    - php: hhvm
    - env: WP_VERSION=master

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script: phpunit

addons:
    code_climate:
        repo_token: e4849ad066dba6c9bcce39d9ec2ac81daf6ef7b020d339c31b6874c2c8bc4d34
